[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rpc-lib"
version = "0.1.0"
description = "SRPC is a lightweight Remote Procedure Call (RPC) library designed for clean abstraction between distributed services or processes, facilitating rapid prototyping."
authors = [{ name="Oseas Andre", email="oseasandrepro@gmail.com" }]
dependencies = ["pytest>=8.4.1"]