[project]
name = "srpcLib"
version = "4.3.1"
description = "SRPC is a lightweight Remote Procedure Call (RPC) library."
authors = [{ name="Oseas Andre", email="oseasandrepro@gmail.com" }]
dependencies = ["msgpack==1.2.1", "mypy==2.3.0"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
srpc-stub-gen = "srpcLib.tools.srpc_stub_gen:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["srpcLib*"]

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
  \.git
 | \.hg
 | \.mypy_cache
 | \.tox
 | \.venv
 | _build
 | buck-out
 | build
 )/
'''
