name: Build and Test [Python 3.13]

on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip intall -e .

      - name: Run linter [flake8]
        run: |
          flake8 .
      - name: Run unit tests
        run: pytest src/tests/unit
        
      - name: Run integration tests
        run: pytest src/tests/integration